spring.application.name=spring-data-mongodb
spring.profiles.active=dev
spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@spring-mongodb.em5a3xd.mongodb.net/${MONGO_DB}?appName=${MONGO_APP}

# Enable this when you want to see the Mongo logs
# logging.level.org.mongodb.driver=DEBUG