spring:
  application:
    name: spring-data-jpa
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

###Define your own
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
